name: Hexo Deploy

on:
  push:
    branches:
      - source  # 这里的名字需对应你存放源码的分支（通常是 main 或 master）

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      # with:
      #   submodules: true #把仓库里的子模块（主题）也一起拉下来
      #   fetch-depth: 0   # 确保拉取完整历史

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # 选择适合 Hexo 的 Node.js 版本

    - name: Install dependencies
      run: npm install

    - name: Deploy Hexo
      env:
        # 这里的名字要和你在第二步设置的 Secret 名字一致
        GH_TOKEN: ${{ secrets.HEXO_DEPLOY_KEY }}  # ${{ secrets.Hexo_Deploy_Key }}   
      run: |
        git config --global user.name "Toothacher"
        git config --global user.email "1943069247@qq.com"
        sed -i "s|github.com|${GH_TOKEN}@github.com|g" _config.yml
        npx hexo clean
        npx hexo deploy